# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KLMCg0lzCrfPePlD82Yd7LNOmhjYc1Kj
"""

# Saudi Stock Market Analysis — FIXED VERSION
# Author: Talah Almualad
# Copy this ENTIRE code into a new Google Colab cell and run

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

print("✅ Step 1: Libraries loaded")

# ── Saudi Stocks ──
stocks = {
    '2222.SR': 'Saudi Aramco',
    '2010.SR': 'SABIC',
    '2380.SR': 'Petro Rabigh',
    '1180.SR': 'Al Rajhi Bank',
    '4300.SR': 'ACWA Power',
    '4050.SR': 'Savola',
    '6050.SR': 'Jarir',
    '7010.SR': 'STC',
    '7020.SR': 'Mobily',
}

RISK_FREE = 0.05
START     = '2021-01-01'
END       = '2024-12-31'

# ── Download Market (EWS = iShares MSCI Saudi Arabia ETF) ──
print("✅ Step 2: Downloading market benchmark (EWS)...")
mkt      = yf.download('EWS', start=START, end=END, auto_adjust=True, progress=False)
mkt_ret  = np.log(mkt['Close'].squeeze() / mkt['Close'].squeeze().shift(1)).dropna()
print(f"   Market data: {len(mkt_ret)} days")

# ── Download Each Stock & Calculate Metrics ──
print("✅ Step 3: Analyzing stocks...")
rows = []

for ticker, name in stocks.items():
    try:
        d = yf.download(ticker, start=START, end=END, auto_adjust=True, progress=False)
        if d.empty or len(d) < 100:
            print(f"   SKIP {name} — no data")
            continue

        ret = np.log(d['Close'].squeeze() / d['Close'].squeeze().shift(1)).dropna()
        df  = pd.concat([ret, mkt_ret], axis=1).dropna()
        df.columns = ['s','m']

        if len(df) < 50:
            print(f"   SKIP {name} — too short")
            continue

        ann_r = df['s'].mean() * 252
        ann_v = df['s'].std()  * np.sqrt(252)
        sh    = (ann_r - RISK_FREE) / ann_v

        b, a, r, _, _ = stats.linregress(df['m'].values, df['s'].values)
        capm = RISK_FREE + b * (df['m'].mean()*252 - RISK_FREE)

        rows.append({
            'Company'    : name,
            'Return_%'   : round(ann_r*100, 2),
            'Volatility' : round(ann_v*100, 2),
            'Sharpe'     : round(sh, 3),
            'Beta'       : round(b,  3),
            'Alpha_%'    : round(a*252*100, 2),
            'CAPM_%'     : round(capm*100, 2),
        })
        print(f"   ✅ {name:20s} Return={ann_r*100:6.1f}%  Sharpe={sh:.3f}  Beta={b:.3f}")

    except Exception as e:
        print(f"   ❌ {name}: {e}")

# ── Results ──
if not rows:
    print("\n❌ No results — check internet connection")
else:
    res = pd.DataFrame(rows).sort_values('Sharpe', ascending=False).reset_index(drop=True)
    res.index += 1
    print(f"\n✅ Step 4: Results ({len(res)} stocks)")
    print(res.to_string())

    # ── Charts ──
    print("\n✅ Step 5: Generating charts...")
    NAVY, BLUE, SKY, RED = '#1B3A5C','#185FA5','#38BDF8','#A32D2D'
    n    = len(res)
    cols = [NAVY,BLUE,'#0A7EA4',SKY,'#0D4F7C','#378ADD','#6BAED6','#9ECAE1','#C6DBEF'][:n]

    fig, axes = plt.subplots(2, 2, figsize=(16, 12))
    fig.suptitle('Saudi Stock Market — CAPM & Risk-Return Analysis\nby Talah Almualad',
                 fontsize=15, fontweight='bold', color=NAVY)

    # 1: Sharpe Ranking
    ax = axes[0,0]
    ax.barh(res['Company'][::-1], res['Sharpe'][::-1], color=cols[::-1])
    ax.axvline(0, color=RED, linestyle='--', linewidth=1.2)
    ax.set_title('Sharpe Ratio Ranking', fontweight='bold', color=NAVY)
    ax.set_xlabel('Sharpe Ratio')

    # 2: Risk vs Return
    ax = axes[0,1]
    sc = ax.scatter(res['Volatility'], res['Return_%'],
                    c=res['Sharpe'], cmap='Blues', s=120,
                    edgecolors=NAVY, linewidths=0.8)
    for _, row in res.iterrows():
        ax.annotate(row['Company'].split()[0],
                    (row['Volatility'], row['Return_%']),
                    textcoords='offset points', xytext=(5,4), fontsize=8)
    plt.colorbar(sc, ax=ax, label='Sharpe')
    ax.axhline(RISK_FREE*100, color=RED, linestyle='--', label='Risk-Free 5%')
    ax.set_title('Risk vs Return', fontweight='bold', color=NAVY)
    ax.set_xlabel('Volatility (%)')
    ax.set_ylabel('Return (%)')
    ax.legend(fontsize=8)

    # 3: Beta
    ax = axes[1,0]
    ax.bar(range(n), res['Beta'],
           color=[NAVY if b>1 else BLUE for b in res['Beta']])
    ax.axhline(1, color=RED, linestyle='--', linewidth=1.2, label='β=1 (Market)')
    ax.set_xticks(range(n))
    ax.set_xticklabels([c.split()[0] for c in res['Company']],
                       rotation=45, ha='right', fontsize=8)
    ax.set_title('CAPM Beta', fontweight='bold', color=NAVY)
    ax.set_ylabel('Beta')
    ax.legend(fontsize=8)

    # 4: Actual vs CAPM
    ax = axes[1,1]
    w  = 0.38
    ax.bar([p-w/2 for p in range(n)], res['Return_%'], w,
           label='Actual', color=NAVY, alpha=0.85)
    ax.bar([p+w/2 for p in range(n)], res['CAPM_%'], w,
           label='CAPM Expected', color=SKY, alpha=0.85)
    ax.set_xticks(list(range(n)))
    ax.set_xticklabels([c.split()[0] for c in res['Company']],
                       rotation=45, ha='right', fontsize=8)
    ax.set_title('Actual vs CAPM Return', fontweight='bold', color=NAVY)
    ax.set_ylabel('Return (%)')
    ax.legend(fontsize=8)

    plt.tight_layout()
    plt.savefig('saudi_stock_analysis.png', dpi=150, bbox_inches='tight', facecolor='white')
    plt.show()

    print("\n✅ Done! Chart saved as 'saudi_stock_analysis.png'")
    print(f"\nBest Sharpe : {res.loc[1,'Company']} ({res.loc[1,'Sharpe']})")
    print(f"Best Return : {res.loc[res['Return_%'].idxmax(),'Company']} ({res['Return_%'].max()}%)")
    print("Analysis by Talah Almualad | github.com/Talah2")